while True:
    try:
        ...
    except ValueError:
        continue